apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: home-assistant
  name: home-assistant
  namespace: longhorn-system
spec:
  engineImage: longhornio/longhorn-engine:v1.0.2
  fromBackup: s3://longhorn@us-east1/backups?backup=backup-044da95bf5514adf&volume=pvc-c89c6feb-b14d-4bcc-aada-f152b9243b4b
  frontend: blockdev
  numberOfReplicas: 2
  size: "5368709120"
  staleReplicaTimeout: 20
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: home-assistant
    namespace: home-assistant
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "20"
    volumeHandle: home-assistant
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.thies.service: home-assistant
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.thies.service: home-assistant
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.thies.service: home-assistant
    spec:
      containers:
      - image: homeassistant/home-assistant
        imagePullPolicy: Always
        name: home-assistant
        ports:
        - containerPort: 8123
          hostPort: 8123
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: config
      dnsConfig: {}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.thies.service: home-assistant
  name: home-assistant
  namespace: home-assistant
spec:
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    io.thies.service: home-assistant
  type: ClusterIP