apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: cloud.broetje-claussen.de
  namespace: ambassador
spec:
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: info@broetje-claussen.de
    privateKeySecret:
      name: https-3a-2f-2facme-2dv02.api.letsencrypt.org-2fdirectory--info-40broetje-2dclaussen.de
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: cloud.broetje-claussen.de
  selector:
    matchLabels:
      hostname: cloud.broetje-claussen.de
  tlsSecret:
    name: broetje-claussen
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: fritzbox.infra.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  hostname: fritzbox.infra.broetje.online
  selector:
    matchLabels:
      hostname: fritzbox.infra.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: gaps.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: gaps.broetje.online
  selector:
    matchLabels:
      hostname: gaps.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: git.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: git.broetje.online
  selector:
    matchLabels:
      hostname: git.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: home.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: home.broetje.online
  selector:
    matchLabels:
      hostname: home.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: monica.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: monica.broetje.online
  selector:
    matchLabels:
      hostname: monica.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: organizr.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: organizr.broetje.online
  selector:
    matchLabels:
      hostname: organizr.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: plex.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  hostname: plex.broetje.online
  selector:
    matchLabels:
      hostname: plex.broetje.online
  tlsSecret:
    name: ambassador-certs
status:
  state: Ready
  tlsCertificateSource: Other
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: rancher.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: rancher.broetje.online
  selector:
    matchLabels:
      hostname: rancher.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: tautulli.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: tautulli.broetje.online
  selector:
    matchLabels:
      hostname: tautulli.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wallabag.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: wallabag.broetje.online
  selector:
    matchLabels:
      hostname: wallabag.broetje.online
  tlsSecret:
    name: ambassador-certs
status:
  state: Ready
  tlsCertificateSource: Other
  
  
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: fritzbox
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: true
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  host: fritzbox.infra.broetje.online
  prefix: /
  service: 192.168.178.1
  use_websocket: true
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: git
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  connect_timeout_ms: 15000
  host: git.broetje.online
  prefix: /
  service: gitea.gitea:3000
  timeout_ms: 15000
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: home-assistant
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  host: home.broetje.online
  prefix: /
  service: home-assistant.home-assistant:8123
  use_websocket: true
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: monica
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  host: monica.broetje.online
  prefix: /
  service: monicahq.monica:80
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: nextcloud
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  connect_timeout_ms: 15000
  host: cloud.broetje-claussen.de
  prefix: /
  service: nextcloud.nextcloud:80
  timeout_ms: 15000
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: nextcloud-private
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  connect_timeout_ms: 15000
  host: cloud.broetje.online
  prefix: /
    remove_response_headers:
    - x-frame-options
  service: nextcloud.nextcloud:80
  timeout_ms: 15000
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: organizr
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  cors:
      origins: https://*.broetje.online,https://app.plex.tv
  host: organizr.broetje.online
  prefix: /
  service: organizr.home:80
  use_websocket: true
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: plex
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: true
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  host: plex.broetje.online
  prefix: /
  service: plex.plex:32400
  use_websocket: true
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: rancher
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  connect_timeout_ms: 15000
  host: rancher.broetje.online
  prefix: /
    remove_response_headers:
    - x-frame-options
  service: rancher.cattle-system:80
  timeout_ms: 15000
  use_websocket: true
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: tautulli
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  host: tautulli.broetje.online
  prefix: /
  service: tautulli.tautulli:8181
  use_websocket: true
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: wallabag
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
    append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  host: wallabag.broetje.online
  prefix: /
  service: wallabag.wallabag:80
  use_websocket: true
