apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: big-storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8000Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: minio-pvc
    namespace: minio
  hostPath:
    path: /mnt/8TB/Kubernetes/Backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 550Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: big-storage
