apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  finalizers:
  - longhorn.io
  labels:
    longhornvolume: organizr
    manager: longhorn-manager
  name: organizr
  namespace: longhorn-system
spec:
  Standby: false
  baseImage: ""
  disableFrontend: false
  engineImage: longhornio/longhorn-engine:v1.0.2
  frontend: blockdev
  nodeID: node2
  numberOfReplicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-home-organizr
  name: organizr
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-home-organizr
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-home-organizr
    spec:
      containers:
      - image: organizr/organizr
        imagePullPolicy: Always
        name: organizr
        ports:
        - containerPort: 80
          name: 80tcp2
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: organizr
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: organizr
        persistentVolumeClaim:
          claimName: organizr
