apiVersion: v1
kind: Namespace
metadata:
  name: bitwarden
---
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: bitwarden
  name: bitwarden
  namespace: longhorn-system
spec:
  Standby: false
  disableFrontend: false
  engineImage: longhornio/longhorn-engine:v1.0.2
  frontend: blockdev
  numberOfReplicas: 2
  size: "1024000000"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 800M
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
    volumeHandle: bitwarden
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.thies.service: bitwarden
  name: bitwarden
  namespace: bitwarden
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 800M
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: bitwarden
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.thies.service: bitwarden
  name: bitwarden
  namespace: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      io.thies.service: bitwarden
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.thies.service: bitwarden
    spec:
      containers:
      - image: bitwardenrs/server-mysql
        imagePullPolicy: Always
        name: bitwarden-rs
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: config
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: bitwarden
---
apiVersion: v1
kind: Service
metadata:
    labels:
      io.thies.service: bitwarden
    name: bitwarden
    namespace: bitwarden
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      io.thies.service: bitwarden
    type: ClusterIP
