apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: bitwarden
  name: bitwarden
  namespace: longhorn-system
spec:
  Standby: false
  disableFrontend: false
  engineImage: longhornio/longhorn-engine:v1.0.2
  frontend: blockdev
  numberOfReplicas: 2
  size: "1024000000"
