apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: bitwarden
  name: bitwarden
  namespace: longhorn-system
spec:
  Standby: false
  disableFrontend: false
  engineImage: longhornio/longhorn-engine:v1.0.2
  frontend: blockdev
  numberOfReplicas: 2
  size: "1024000000"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 800M
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
    volumeHandle: bitwarden
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
