apiVersion: getambassador.io/v2
kind: Host
metadata:
  labels:
    io.thies.service: archivy
  name: archivy.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  hostname: archivy.broetje.online
  selector:
    matchLabels:
      hostname: archivy.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    io.thies.service: archivy
  name: archivy
  namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  connect_timeout_ms: 15000
  host: archivy.broetje.online
  prefix: /
  remove_response_headers:
  - x-frame-options
  service: archivy.archivy:5000
  timeout_ms: 15000
