apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: monica.broetje.online
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  ambassadorId:
  - default
  hostname: monica.broetje.online
  selector:
    matchLabels:
      hostname: monica.broetje.online
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: monica
    namespace: ambassador
spec:
  add_response_headers:
    Content-Security-Policy:
      append: false
      value: frame-ancestors  https://*.broetje.online;
    Strict-Transport-Security: max-age=31536000;
  host: monica.broetje.online
  prefix: /
  service: monicahq.monica:80
